server:
  port: 8080
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/wechatnoteplatform?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml #扫描xml所在的包
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  type-aliases-package: com.wonder.entity #扫描实体类所在的包